title: The Chuvash Calendar | Чӑваш ҫулталӑк хисепӗ
description: The traditional Chuvash Calendar is a lunisolar calendar | Чӑвашсен йӑлана кӗнӗ уйӑх-хӗвел ҫулталӑк хисепӗ.
author:
  name: metri
theme: minima

plugins:
  - jekyll-seo-tag

minima:
  skin: auto

