title: The Chuvash Calendar | Чӑваш ҫулталӑк хисепӗ
description: The traditional Chuvash Calendar is a lunisolar calendar | Чӑвашсен йӑлана кӗнӗ уйӑх-хӗвел ҫулталӑк хисепӗ.
theme: jekyll-theme-tactile

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - LICENSE.md
  - year-table.md
